application: research-engine
version: 0
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
  secure: always

- url: /static
  static_dir: static
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /cron/.*
  script: main.app
  login: admin

- url: /.*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: latest